database.name=${env:JAMES_DB_NAME:-james}
database.schema=public
database.host=${env:JAMES_DB_HOST:-postgres}
database.port=5432
database.username=${env:JAMES_DB_USER:-james}
database.password=${env:JAMES_DB_PASSWORD}
row.level.security.enabled=false
pool.initial.size=5
pool.max.size=15
ssl.mode=allow
